### ISSUE TITLE
radar data of one chirp

### ISSUE THREAD

**Issue by chiyukunpeng** [yizhou-wang/cruw-devkit#10]
Hi, it is a good work!

The shape of chirp data is `128x128x2` in `000000_0000.npy`. What are the meaning of `chirp[:,:,0]` and `chirp[:,:,1]`?

Thanks!

**Comment by ElsayedMMohammed** [comment]
If you found an answer, please let me know.

**Comment by yizhou-wang** [comment]
The two channels are real and imaginary parts of the values after FFTs mentioned in Section 3.1 in [this paper](https://openaccess.thecvf.com/content/WACV2021/html/Wang_RODNet_Radar_Object_Detection_Using_Cross-Modal_Supervision_WACV_2021_paper.html).
