### ISSUE TITLE
Details about confidence map mapping

### ISSUE THREAD

**Issue by zhengzangw** [yizhou-wang/cruw-devkit#3]
Can you explain or show reference on how range and angle are mapped in the code below?

https://github.com/yizhou-wang/cruw-devkit/blob/a565905d52c0962a632ef3779d88e66c910ea171/cruw/mapping/generate_grids.py#L6

or if you can explain the meaning of the keywords in `radar_cfg` in `sensor_config_rod2021`. It would be of great help to understand the mapping process. Thanks in advance.

**Comment by yizhou-wang** [comment]
Please take a look at the tutorial Ln[7]-[10]: https://github.com/yizhou-wang/cruw-devkit/blob/master/tutorials/cruw_devkit_tutorial_rod2021.ipynb. Free to raise questions if you still have any questions.

**Comment by zhengzangw** [comment]
Thanks! I've run the notebook, and the tutorial is really great. As I understand, the radar information provided in numpy has the index generated according to function `confmap2ra`, while the annotation is provided as the raw data (so it needs to be transformed to index)

My question is, what's the logic behind the mapping in `confmap2ra` function. For example, what is the meaning of `crop_num` and `freq_res`. Is there any reference for this transformation?

Besides, it seems `range/angle_grid_label` has no further usage. Is there any difference between it and `range/angle_grid`?

**Comment by yizhou-wang** [comment]
Those parameters are the radar hardware/preprocessing configurations that you do not need to take care of. The generated grid is a fixed mapping when the radar sensor is properly setup.

As for the `range/angle_grid_label`, yes, they are deprecated and not for ROD2021 Challenge's use.

**Comment by zhengzangw** [comment]
Cool! Thanks a lot.
