### ISSUE TITLE
How AP is computed?

### ISSUE THREAD

**Issue by zhengzangw** [yizhou-wang/cruw-devkit#5]
According to the essay, AP and AR are the average precision and recall among different OLS threshold. As I understand, the precision should be total True Positive(TP) over TP+FP and recall should be total TP over the number of ground truth. In the code, the recall seems to be calculated in this way, while the precision is averaged over another dimension `R`.

https://github.com/yizhou-wang/cruw-devkit/blob/a565905d52c0962a632ef3779d88e66c910ea171/cruw/eval/rod/rod_eval_utils.py#L164

This dimension seems to be calculated with recall and `recThrs`. I wonder what's the meaning of this dimension and is the precision consistent with the classic definition? Also, is this AP the metric used in the ROD2021 competition?

Thanks in advance!

**Comment by yizhou-wang** [comment]
The code for AP and AR in our evaluation script is modified from the COCO evaluation script: https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py. 

In the traditional object detection community, AP is defined as the area under the precision-recall curve. The following blog might be helpful to know the detailed definition: https://jonathan-hui.medium.com/map-mean-average-precision-for-object-detection-45c121a31173

**Comment by zhengzangw** [comment]
That's a great help. Thank you very much!
