### ISSUE TITLE
Questions about the format of the dataset

### ISSUE THREAD

**Issue by yaoshanliang** [yizhou-wang/cruw-devkit#8]
I have downloaded the dataset from your website. The format is shown below. 
![image](https://user-images.githubusercontent.com/5028569/114960979-b42e0880-9e9a-11eb-9db1-5835130ed095.png)

In file `cruw_devkit_tutorial_rod2021.ipynb`, the format is 
![image](https://user-images.githubusercontent.com/5028569/114960850-703b0380-9e9a-11eb-91e2-68ab2f9cffc5.png)

Do I need to transfer the downloaded dataset into the format in the ipynb file?
Is the transfer script already provided?

**Comment by yizhou-wang** [comment]
Please refer to https://github.com/yizhou-wang/RODNet/issues/19#issuecomment-833650739.
